/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package matricula;

import javax.swing.JOptionPane;

/**
 *
 * @author Jimena
 */
public class formMaterias extends javax.swing.JFrame {

    /**
     * Creates new form formMaterias
     */
    
    public formMaterias() {
        
        initComponents();
        botonGrupMat.add(mat1);
        botonGrupMat.add(mat2);
        botonGrupMat.add(mat3);
        botonGrupMat.add(mat4);
        botonGrupMat.add(mat5);
        botonGrupMat.add(mat7);
        botonGrupMat.add(mat8);
        botonGrupMat.add(mat9);
        botonGrupMat.add(mat10);
        botonGrupMat.add(mat6);
        
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonGrupMat = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        mat1 = new javax.swing.JRadioButton();
        mat2 = new javax.swing.JRadioButton();
        mat4 = new javax.swing.JRadioButton();
        mat5 = new javax.swing.JRadioButton();
        mat3 = new javax.swing.JRadioButton();
        mat9 = new javax.swing.JRadioButton();
        mat7 = new javax.swing.JRadioButton();
        mat8 = new javax.swing.JRadioButton();
        mat6 = new javax.swing.JRadioButton();
        mat10 = new javax.swing.JRadioButton();
        siguienteBT = new javax.swing.JButton();
        terminarBT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel6.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel6.setText("Seleccione la materia que desea matricular:");

        jLabel1.setFont(new java.awt.Font("Eras Bold ITC", 0, 36)); // NOI18N
        jLabel1.setText("Selección de Materias");

        mat1.setText("Programación II");
        mat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mat1ActionPerformed(evt);
            }
        });

        mat2.setText("Lectura Crítica II");
        mat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mat2ActionPerformed(evt);
            }
        });

        mat4.setText("Ciudadanía del siglo 21");
        mat4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mat4ActionPerformed(evt);
            }
        });

        mat5.setText("Lengua Extranjera I");
        mat5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mat5ActionPerformed(evt);
            }
        });

        mat3.setText("Física II");

        mat9.setText("Programación II");
        mat9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mat9ActionPerformed(evt);
            }
        });

        mat7.setText("NomMateria");
        mat7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mat7ActionPerformed(evt);
            }
        });

        mat8.setText("Programación II");
        mat8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mat8ActionPerformed(evt);
            }
        });

        mat6.setText("Programación II");
        mat6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mat6ActionPerformed(evt);
            }
        });

        mat10.setText("Programación II");
        mat10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mat10ActionPerformed(evt);
            }
        });

        siguienteBT.setText("Siguiente");
        siguienteBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteBTActionPerformed(evt);
            }
        });

        terminarBT.setText("Terminar");
        terminarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terminarBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(mat1)
                                        .addComponent(mat3)
                                        .addComponent(mat5)
                                        .addComponent(mat4)
                                        .addComponent(mat2))
                                    .addGap(128, 128, 128)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(mat8)
                                        .addComponent(mat7)
                                        .addComponent(mat9)
                                        .addComponent(mat6)
                                        .addComponent(mat10))))
                            .addComponent(jLabel1))
                        .addContainerGap(111, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(terminarBT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(siguienteBT)
                        .addGap(64, 64, 64))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mat1)
                    .addComponent(mat7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mat2)
                    .addComponent(mat8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mat9)
                    .addComponent(mat3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mat10)
                    .addComponent(mat4))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mat6)
                    .addComponent(mat5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(terminarBT)
                    .addComponent(siguienteBT))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mat1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mat1ActionPerformed

    private void mat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mat2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mat2ActionPerformed

    private void mat4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mat4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mat4ActionPerformed

    private void mat5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mat5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mat5ActionPerformed

    private void mat9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mat9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mat9ActionPerformed

    private void mat7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mat7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mat7ActionPerformed

    private void mat8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mat8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mat8ActionPerformed

    private void mat6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mat6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mat6ActionPerformed

    private void mat10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mat10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mat10ActionPerformed

    private void siguienteBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteBTActionPerformed
        Materias materia= new Materias();
        if(mat1.isSelected()){
            materia.setNombreMat("Calculo Integral");          
        }
        if(mat2.isSelected()){
            materia.setNombreMat("Ciudadania");          
        }
        if(mat3.isSelected()){
            materia.setNombreMat("Lectura Crítica");          
        }
        if(mat4.isSelected()){
            materia.setNombreMat("Fisica 2");          
        }
        if(mat5.isSelected()){
            materia.setNombreMat("Ingles 1");          
        }
        if(mat6.isSelected()){
            materia.setNombreMat("Programación 2");          
        }
       materia.getNombreMat();
       Materia mat=new Materia(materia);
       this.setVisible(false);
       mat.setVisible(true);
       
       
    }//GEN-LAST:event_siguienteBTActionPerformed

    private void terminarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terminarBTActionPerformed
       MostrarHorario mosHor=new MostrarHorario();
       int r = JOptionPane.showConfirmDialog(null, "¿Desea terminar el proceso de matricula de materias?");
        if (r == 0) {
            this.setVisible(false);
            mosHor.setVisible(true);
        }
        
    }//GEN-LAST:event_terminarBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formMaterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formMaterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formMaterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formMaterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formMaterias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup botonGrupMat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton mat1;
    private javax.swing.JRadioButton mat10;
    private javax.swing.JRadioButton mat2;
    private javax.swing.JRadioButton mat3;
    private javax.swing.JRadioButton mat4;
    private javax.swing.JRadioButton mat5;
    private javax.swing.JRadioButton mat6;
    private javax.swing.JRadioButton mat7;
    private javax.swing.JRadioButton mat8;
    private javax.swing.JRadioButton mat9;
    private javax.swing.JButton siguienteBT;
    private javax.swing.JButton terminarBT;
    // End of variables declaration//GEN-END:variables
}
